name: Pull Requests

on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  GOFLAGS: -mod=readonly
  GOPROXY: https://proxy.golang.org

jobs:
  pull-request:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.3.0
      - uses: actions/setup-go@v3
        with:
          cache: true
          check-latest: true
          go-version-file: 'go.mod'
      - name: Run go mod tidy
        run: |
          go mod tidy
          git diff --exit-code
      - uses: golangci/golangci-lint-action@v3
      - name: Run go test
        run: |
          go test -v ./...

